# Do const current scans or const height scans
# Option 1: do const current scans, then edit 'StartBias_mV', 'EndBias_mV', 'StartCurrent_pA', 'EndCurrent_pA'
# Option 2: do const height scans, then edit 'StartHeight', 'EndHeight'
# Total_steps is the total number of images to take,
# The program will do a even division between 'Start' and 'End' values,
# For example 
# Total_steps = 5, StartBias_mV = 30, EndBias_mV = 10
# The program will do [30, 25, 20, 15, 10] for data collection 

CH_AFM : 1 # 1 For const height scans, 0 for const current scans
Total_steps: 2 # total number of images to take


# Option 1
# const current scan, bias in mV
StartBias_mV: 100
EndBias_mV: 100
# const current scan, current in pA
StartCurrent_pA: 100
EndCurrent_pA: 100


# Option 2
# const height scan, height range in Angstrom
StartHeight: 0.0
EndHeight:  0.0
# bias range for const height scan
Bias_Range_mV: [0] #List every bias, needs at leat one element


g_filename_len: 18 # The last 18 char is sth. like A191214.245959.dat


#Use one image as a template. Before each scan, use the parameters of the template to scan the current location, then use phase-correlation to find where to move,
#so that after the movement, the new location is the same as the template.

g_reposition_delay: 5 #seconds before reposition for alignment to template

#template file, const current scan
template_file: ''
template_folder: ''

use_last_as_template: True

shift_reg_channel: [0] # List of channel number for shift registration, i.e. alignment
subpixel_reg: 1 # precision for alignment, use 1, 10 or 100, not in use

deltaX_dac: 16 #pixel size in x
Chmode:
    mode: 0 # 1 for const height, 0 for const current
    ddeltaX: 128    #scan speed
    channels_code: 0x0000001F

Ccmode:
    mode: 0
    ddeltaX: 32
    channels_code: 0x0000001F